config/routes.rb
SquidBox::Application.routes.draw do

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'user_sessions/create' => "user_sessions#create", :as => :create_user_sessions

  match "repository/:id/commit/:commit_id" => "repository_commit#show"

  resources :repositories
  resources :comments

  root :to => 'home#index', :as => :home

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :start_line, :end_line, :file, :commit, :repository_id, :commit

  def line_length
    end_line - start_line
  end
end

app/models/repository.rb
require 'fileutils'

class Repository < ActiveRecord::Base
  attr_accessible :name, :path, :private

  validates_presence_of :name, :path

  before_save :generate_ssh_keys
  after_validation :ensure_repository_exists

  def is_path_uri?
    errors.add(:path, "not a valid url") unless Repository.uri?(self.path)
  end

  def is_path_git_repo?
    errors.add(:path, "not a valid git repo") unless Repository.is_git_repo?(self.path)
  end

  def generate_local_path
    "./repos/#{id}"
  end

  def description
    repo.description
  end

  def generate_ssh_keys
    return unless self.private?
    return if self.public_key.present? && self.private_key.present?

    key = SSHKey.generate

    self.private_key = key.private_key
    self.public_key = key.ssh_public_key
  end

  def ensure_repository_exists
    if File.directory? generate_local_path
      begin
        if repo.config["remote.origin.url"] == path
          self.has_local_clone = true
          return
        end
      rescue
      end

      FileUtils.rm_rf generate_local_path
    end

    Dir.mkdir "./repos" unless File.directory? "./repos"
    Dir.mkdir generate_local_path unless File.directory? generate_local_path

    Dir.mkdir "./keys" unless File.directory? "./keys"
    Dir.mkdir "./keys/#{id}" unless File.directory? "./keys/#{id}"

    File.open(private_key_path, "w") do |private_key_file|
      private_key_file << private_key
    end
    File.chmod 0600, private_key_path

    self.is_cloning = true

    begin
      clone
    rescue
    end

    self.is_cloning = false

    begin
      self.has_local_clone = false

      repo.present?

      self.has_local_clone = true
    rescue
    end

  end

  def private_key_path
    "./keys/#{id}/private_key"
  end

  def clone
    clone_command = "git clone #{path} #{generate_local_path}"
    final_command = clone_command
    if self.private?
      final_command = "ssh-agent bash -c 'ssh-add -D; ssh-add #{private_key_path}; #{clone_command}'"
    end

    puts final_command
    system final_command
  end

  def commits(offset = 0, per_page = 10)
    repo.commits('master', per_page, offset * per_page)
  end

  def total_commits
    repo.commit_count
  end

  def find_commit(commit_id)
    repo.commit(commit_id)
  end

  private

  def repo
    @repo ||= Grit::Repo.new(generate_local_path)
  end

  def remote_repo
    @remote_repo ||= Grit::Git.new(path)
  end

  def self.is_git_repo?(path)
    remotes = Grit::Git.new(path).run('', 'ls-remote "' + path + '"', '', {}, {})
    remotes.present?
  end

  def self.uri?(string)
    uri = URI.parse(string)
    %w( http https git ).include?(uri.scheme)
  rescue URI::BadURIError
    false
  rescue URI::InvalidURIError
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user_session, :current_user

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new

    render :partial => "new"
  end

  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      html = render_to_string :partial => "comments/line", :locals => {:comment => @comment}

      render :json => {:success => true, :data => html}
    else
      render :json => {:success => false}
    end
  end

  def show
    comment = Comment.find(params[:id])

    render :partial => "show", :locals => {:comment => comment}
  end

  def index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    render :nothing => true, :status => :ok
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/repositories_controller.rb
require 'will_paginate/array'

class RepositoriesController < ApplicationController
  def new
    @repository = Repository.new
  end

  def create
    @repository = Repository.new(params[:repository])

    if @repository.save
      redirect_to @repository, :notice => "Repository Created"
    else
      render :new
    end
  end

  def index
    @repositories = Repository.all
  end

  def show
    @repository = Repository.find(params[:id])
    @repository.ensure_repository_exists

    if @repository.has_local_clone?
      page = params[:page] ? params[:page] : 1
      @commits = @repository.commits(page.to_i - 1)
      @commit_pagination = WillPaginate::Collection.new(page, 10, @repository.total_commits)
    end
  end
end

app/controllers/repository_commit_controller.rb
class RepositoryCommitController < ApplicationController
  def show
    @repository = Repository.find params[:id]
    @commit = @repository.find_commit params[:commit_id]
    @comments = Comment.find_all_by_commit(@commit.id)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Log in successful"
      redirect_to home_path
    else
      flash[:error] = "Invalid Login"
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy

    flash[:notice] = "Log out successful"
    redirect_to home_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for model_instance
    if model_instance.errors.any?
      render :partial => 'error_messages', :locals => { :errors => model_instance.errors }
    end
  end

  def messages flash
    render :partial => 'messages', :locals => {:flash => flash}
  end

  def navigation_menu
      menu_items = [ { :text => "Home", :path => home_path },
                     { :text => "Repositories", :path => repositories_path } ]

      html_class = menu_items.each_with_object({}) do |item, hash|
        text = item[:text]
        first_path_segment = "/#{request.path.split('/')[1]}" # /tournaments/introduction returns "/tournaments"
        hash[text] = first_path_segment == item[:path] ? 'selected' : ''
      end

      render :partial => "navigation", :locals => { :menu_items => menu_items, :html_class => html_class }
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper

  def trim_string(string, length)
    if string.length > length
      "#{string[0..length]} ..."
    else
      string
    end
  end

end

app/helpers/repository_commit_helper.rb
module RepositoryCommitHelper

  # remove +/- or wrap in html
  def clean_line(line)
    line.sub(/^./, '').chomp
  end

  def produce_full_unified_diff(diff)
    produce_diff diff
  end

  def produce_context_unified_diff(diff)
    produce_diff diff, {:diff => %W(-U 10), :include_diff_info => true}
  end

  def find_line_type(line)
    case line
      when /^(---|\+\+\+|\\\\)/
        :comment
      when /^\+/
        :added
      when /^-/
        :deleted
      when /^ /
        :unchanged
      when /^@@/
        :block_info
      else
        :unknown
    end
  end

  def before_start_line(line)
    line.match(/@@ -(\d+).*\+(\d+),.*/)[1].to_i
  end

  def after_start_line(line)
    line.match(/@@ -(\d+).*\+(\d+),.*/)[2].to_i
  end

  private
  def produce_diff(diff, options = {})
    original = diff.a_blob.nil? ? nil : diff.a_blob.data
    changed = diff.b_blob.nil? ? nil : diff.b_blob.data

    Diffy::Diff.new original, changed, {:allow_empty_diff => true}.merge(options)
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/application/_error_messages.html.haml
#error_messages
  %p Please fix the following errors:
  %ul
    - errors.full_messages.each do |message|
      %li= message

app/views/application/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/application/_navigation.html.haml
#navigation
  %ul.nav
    - menu_items.each do |menu_item|
      %li{ :class => html_class[menu_item[:text]] }
        = link_to menu_item[:text], menu_item[:path]

app/views/comments/_line.html.haml
= link_to "#", :data => {:id => comment.id, :file => comment.file,
                         :start => comment.start_line, :end => comment.end_line} do
  %i.icon-list

app/views/comments/_new.html.haml
%tr.new-comment-row
  %td.add_comment
  %td.line-number-after.line-number
  %td.line-number-before.line-number
  %td.line
    .commit-comment
      = form_for @comment do |f|
        = f.hidden_field :start_line
        = f.hidden_field :end_line

        = f.hidden_field :file
        = f.hidden_field :commit
        = f.hidden_field :repository_id

        .content
          = f.text_area :content

        .controls
          .action
            = link_to "#", :id => "save_new_comment" do
              .btn.btn-primary
                Create

          .close-comment
            = link_to "#", :id => "close_new_comment" do
              .btn.btn-danger
                Cancel

  %td.comments

app/views/comments/_show.html.haml
%tr.show-comment-row{:data => {:id => comment.id}}
  %td.add_comment
  %td.line-number-after.line-number
  %td.line-number-before.line-number
  %td.line
    .commit-comment
      .content.well
        = comment.content

      .controls
        .action
          .btn.btn-warning
            Edit

        .action
          = link_to comment, :method => :delete, :remote => true, :id => "delete_commit_comment" do
            .btn.btn-danger
              Delete

        .close-comment
          = link_to "#", :remote => true, :id => "close_commit_comment" do
            .btn.btn-info
              Close

  %td.comments

app/views/home/index.html.haml
%h1 Squid Box

- if current_user_session.nil?
  .login
    = render :partial => "user_sessions/login", :locals => {:user_session => UserSession.new}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title Squid Box
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = yield(:head)

  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = navigation_menu

    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              #flash
                = messages flash

              = yield
          %footer

app/views/repositories/_list_commits.html.haml
.commits
  %h2
    Commits

  %table.table
    %thead
      %tr
        %th
          Date
        %th
          Author
        %th
          Message
        %th
          Changes
        %th
          Commit
    - @commits.each do |commit|
      %tr.commit{:data => {:url => "/repository/#{@repository.id}/commit/#{commit.id}"}}
        %td
          #{I18n.l commit.date, :format => :short}

        %td
          #{trim_string commit.author.name, 20}

        %td.name
          #{trim_string commit.short_message, 120}

        %td
          .added
            + #{commit.stats.additions}
          .deleted
            = "- #{commit.stats.deletions}"

        %td
          #{commit.id_abbrev}

  = will_paginate @commit_pagination

app/views/repositories/index.html.haml
%h1 Repositories

= link_to new_repository_path, :id => "new_repository_link" do
  .btn.btn-primary.new-repository
    Add Repository

%table.repositories.table
  %thead
    %tr
      %th
        Repository
      %th
        Source

  - @repositories.each do |repository|
    %tr
      %td
        = repository.name
      %td
        = repository.path
      %td
        = link_to "View", repository_path(repository)

app/views/repositories/new.html.haml
%h1 New Repository

= error_messages_for @repository

= form_for @repository do |f|
  = f.label :name
  = f.text_field :name

  = f.label :path
  = f.text_field :path

  = f.label :private
  = f.check_box :private

  = f.submit

app/views/repositories/show.html.haml
%h1
  = @repository.name

- if @repository.has_local_clone
  = render :partial => "list_commits"
- else
  - if @repository.is_cloning

    Cloning Repository...

  - else

    Unable to clone repository, please try the following:
    %ul
      %li
        Check that the Path is correct
      - if @repository.private?
        %li
          Please try the adding the following public key to your repository ssh keys

    - if @repository.private?
      = text_area_tag "ssh-public-tag", @repository.public_key

    = link_to_function "Try Cloning Again", repository_path(@repository)

app/views/repository_commit/_commit_diff.html.haml
.diff.well
  %table
    - before_count = 1
    - after_count = 1
    - line_count = 1

    - diff.each do |line|

      - line_comments = comments.find_all{|comment| line_count == comment.start_line}

      %tr.code{:data => {:line => line_count}}
        - line_count += 1
        %td.add_comment
          = link_to "+", "#"
        %td.line-number-after.line-number
          #{after_count}
        %td.line-number-before.line-number
          #{before_count}

        - case line
        - when /^(---|\+\+\+|\\\\)/
          - before_count += 1
          - after_count += 1
          %td.line.diff-comment
            %pre.prettyprint
              #{line.chomp}
            .comment-line-background
        - when /^\+/
          - after_count += 1
          %td.line.ins
            %pre.prettyprint
              #{clean_line line}
            .comment-line-background
        - when /^-/
          - before_count += 1
          %td.line.del
            %pre.prettyprint
              #{clean_line line}
            .comment-line-background
        - when /^ /
          - before_count += 1
          - after_count += 1
          %td.line.unchanged
            %pre.prettyprint
              #{clean_line line}
            .comment-line-background
        - when /^@@/
          - before_count += 1
          - after_count += 1
          %td.line.diff-block-info
            %pre.prettyprint
              #{line.chomp}
            .comment-line-background
        - else
          %td.line

        %td.comments
          - line_comments.each do |line_comment|
            = render :partial => "comments/line", :locals => {:comment => line_comment}

app/views/repository_commit/_unified_context_diff.html.haml
.diff.well
  %table

    - before_count = 0
    - after_count = 0
    - line_count = 1

    - diff.each do |line|
      - line_type = find_line_type line

      - if [:block_info].include? line_type
        - puts line
        - before_count = before_start_line(line) - 1
        - after_count = after_start_line(line) - 1

      - if [:added, :deleted, :unchanged].include? line_type
        - if [:added, :unchanged].include? line_type
          - after_count += 1
        - if [:deleted, :unchanged].include? line_type
          - before_count += 1

        %tr.code{:data => {:line => line_count}}
          - line_count += 1

          %td.add_comment
            = link_to "+", "#"

          %td.line-number-before.line-number
            - if line_type == :added
              = "-"
            - else
              #{before_count}

          %td.line-number-after.line-number
            - if line_type == :deleted
              = "-"
            - else
              #{after_count}

          - case line
          - when /^\+/
            %td.line.ins
              %pre.prettyprint
                #{clean_line line}
              .comment-line-background
          - when /^-/
            %td.line.del
              %pre.prettyprint
                #{clean_line line}
              .comment-line-background
          - when /^ /
            %td.line.unchanged
              %pre.prettyprint
                #{clean_line line}
              .comment-line-background
          - else
            %td.line

          %td.comments
            - line_comments = comments.find_all{|comment| line_count == comment.start_line}
            - line_comments.each do |line_comment|
              = render :partial => "comments/line", :locals => {:comment => line_comment}

app/views/repository_commit/_unified_full_diff.html.haml
.diff.well
  %table

    - before_count = 1
    - after_count = 1
    - line_count = 1

    - diff.each do |line|
      - puts line
      - line_comments = comments.find_all{|comment| line_count == comment.start_line}

      %tr.code{:data => {:line => line_count}}
        - line_count += 1
        %td.add_comment
          = link_to "+", "#"
        %td.line-number-after.line-number
          #{after_count}
        %td.line-number-before.line-number
          #{before_count}

        - case line
        - when /^(---|\+\+\+|\\\\)/
          - before_count += 1
          - after_count += 1
          %td.line.diff-comment
            %pre.prettyprint
              #{line.chomp}
            .comment-line-background
        - when /^\+/
          - after_count += 1
          %td.line.ins
            %pre.prettyprint
              #{clean_line line}
            .comment-line-background
        - when /^-/
          - before_count += 1
          %td.line.del
            %pre.prettyprint
              #{clean_line line}
            .comment-line-background
        - when /^ /
          - before_count += 1
          - after_count += 1
          %td.line.unchanged
            %pre.prettyprint
              #{clean_line line}
            .comment-line-background
        - when /^@@/
          - before_count += 1
          - after_count += 1
          %td.line.diff-block-info
            %pre.prettyprint
              #{line.chomp}
            .comment-line-background
        - else
          %td.line

        %td.comments
          - line_comments.each do |line_comment|
            = render :partial => "comments/line", :locals => {:comment => line_comment}

app/views/repository_commit/show.html.haml
%h2
  #{@commit.message}

.author
  #{@commit.author}

.date
  #{I18n.l @commit.date, :format => :short}

.commit-id
  Commit #{@commit.id}

.change-stats
  .added
    + #{@commit.stats.additions}
  .deleted
    = "- #{@commit.stats.deletions}"

.diffs{:data => {:repository => @repository.id, :commit => @commit.id}}
  - @commit.diffs.each do |diff|

    .file-diff{:data => {:file => diff.b_path}}
      - comments = @comments.find_all { |comment| comment.file == diff.b_path }
      %br

      .file-name
        %h3
          - if diff.a_path != diff.b_path
            #{diff.a_path} ==> #{diff.b_path}
          - else
            = diff.b_path

      .container.line-diff{:data => {:file => diff.b_path}}
        -#= render :partial => "unified_full_commit_diff", :locals => {:diff => produce_full_unified_diff(diff),
        -#                                                             :comments => comments}
        = render :partial => "unified_context_diff", :locals => {:diff => produce_context_unified_diff(diff),
                                                                 :comments => comments}

app/views/user_sessions/_login.html.haml
- user_session ||= @user_session

= form_for user_session, :url => create_user_sessions_path do |f|
  .field
    .username
      = f.label :login
      = f.text_field :login

    .password
      = f.label :password
      = f.password_field :password

    .actions
      = f.submit "Login"

app/views/user_sessions/new.html.haml
= render :partial => "login"